### ISSUE TITLE
Unity installation proposal

### ISSUE THREAD

**Issue by KonH** [GabLeRoux/unity3d-ci-example#10]
Hello! I have investigated Unity installation on CI (https://github.com/KonH/UnityCiPipeline) and found a nice tool for it - https://github.com/DragonBox/u3d. It provides the ability to install all available Unity versions without manual link and checksum management.
I think it can improve your project usability in some way.
In my approach required version of Unity (detected by ProjectVersion.txt) is installed on every build, because I don't want to have several versions of my docker container. But I don't think that it is a good idea in common (build time noticeable increased), so you can implement it into your CI generator to support more versions.
I hope this information will be useful to you.

**Comment by GabLeRoux** [comment]
Oh sweet, thanks for sharing this 👍 I'll definitely need to give this a try. There's even a fastlane plugin in there, sounds great!

I'm closing this issue here, but I'll see what can be done in the following weeks for this.
