### ISSUE TITLE
Docker container unity3d:2019.3.0f6 missing platforms support

### ISSUE THREAD

**Issue by L4ZZA** [GabLeRoux/unity3d-ci-example#16]
Steps:
1. Run  `docker run -it gableroux/unity3d:2019.3.0f6`
2. Once machine as started run `ls /opt/Unity/Editor/Data/PlaybackEngines/`
![image](https://user-images.githubusercontent.com/17835185/77853382-cbd91700-71db-11ea-885a-27c548a18c2c.png)
Only the linux standalone support is available I was expecting all the platforms supported.
If that is not possible I would expect more containers in [here](https://hub.docker.com/r/gableroux/unity3d/tags?page=1&name=2019.3.0f6) so that you can have more options like:
unity3d:2019.3.0f6-window-osx
unity3d:2019.3.0f6-linux-osx
unity3d:2019.3.0f6-linux-window-osx

I'm following this [tutorial](https://www.youtube.com/watch?v=-txXtAfViEQ) but using the latest unity version at the moment.

P.S I didn't know where to raise this in the docker platform

**Comment by GabLeRoux** [comment]
Moved issue to gitlab where home of docker image project is:  
https://gitlab.com/gableroux/unity3d/-/issues/69

👍
