### ISSUE TITLE
Licensing::Module] License is not active (com.unity.editor.ui). HasEntitlements will fail.

### ISSUE THREAD

**Issue by anutting** [GabLeRoux/unity3d-ci-example#18]
I'm running a Unity Build within an Ubuntu container based on your Dockerfile. The error in the title is all over the place in the logs and I'm not exactly sure what's causing it. Would you have any ideas? I may be running into [this issue](https://issuetracker.unity3d.com/issues/cannot-activate-license-within-a-docker-container).

Here's the full build command:
```
RUN xvfb-run --auto-servernum --server-args="-screen 0 640x480x24" /unity/Editor/Unity -projectPath /project -quit -batchmode -buildTarget webgl -serial "${UNITY_SERIAL}" -username "${UNITY_USER}" -password "${UNITY_PASS}" -executeMethod BuildUtils.BuildWithParams 
```
any help would be appreciated.

Thanks

**Comment by GabLeRoux** [comment]
Hi, main repo for this project can be found on gitlab as github is only a fork to test travis integration. Here it is:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example

I think the following issue may have related infos:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/103

issues related to activation:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues?scope=all&state=all&label_name[]=activation

also, be sure to provide your unity version. Here are some generic questions that should help you:

* Which CI Service are you using?



* Which docker image are you using?



* Did it work with a previous version?



* Do you have a link to your failing pipeline or job?



* What's the full output log?
