### ISSUE TITLE
Does it work for free accounts on Unity 2018 and 2019?

### ISSUE THREAD

**Issue by lemikistu** [GabLeRoux/unity3d-ci-example#9]
Hi I was wondering whether  we can use this steps including license part to generate license for free Unity account to use for Unity 2018 and 2019 project or is ci only works for unity pro accounts?

**Comment by GabLeRoux** [comment]
Sure, works for free account. Have a look [at the gitlab remote](https://gitlab.com/gableroux/unity3d-gitlab-ci-example) for more up to date values or more answers. There is still a work in progress branch for 2019, but some folks confirmed they got it to work with 2019 too.

No need for pro at all and depending on the CI and git hosting service (github or gitlab), if you go public, you have access to unlimited free CI. In case of private, CircleCI can provide a free runner and gitlab-ci offers 2000 free minutes. In the case of gitlab-ci, it's more performant to use your own runners. 👍

**Comment by lemikistu** [comment]
@GabLeRoux Thanks a lot for the answer.
